config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :chat_rooms, only: [:new, :create, :show, :index]
  
  root to: 'chat_rooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  
  validates :body, presence: true, length: {minimum: 2, maximum: 1000}
  
  after_create_commit { MessageBroadcastJob.perform_later(self) }
  
  def timestamp
    created_at.in_time_zone(user.time_zone || Time.zone.name).strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  devise :omniauthable, :omniauth_providers => [:facebook, :google_oauth2, :twitter]
  
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  
  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_create do
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout :layout_by_resource
  before_action :authenticate_user!
  before_filter :set_time_zone

  def set_time_zone
    #current user is a devise method see https://github.com/plataformatec/devise
    Time.zone = current_user.time_zone if current_user
  end
  
  protected
    def layout_by_resource
      if devise_controller?
        "devise"
      else
        "application"
      end
    end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = ChatRoom.all
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = ""
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])
    
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Google") if is_navigational_format?
    else
      session["devise.google_data"] = ""
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
  def twitter
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = ""
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}", opts
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/chat_rooms/_chat_room.html.erb
<li><%= link_to "#{chat_room.title}", chat_room_path(chat_room) %></li>

app/views/chat_rooms/index.html.erb
<div>
  Hello <%= current_user.name %>!
  <br />
  <%= link_to t('.sign_out', default: 'Sign out'), destroy_user_session_path, method: :delete %>
</div>

<h1>Chat rooms</h1>

<p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>

<ul>
  <%= render @chat_rooms %>
</ul>

app/views/chat_rooms/new.html.erb
<h1>Add chat room</h1>

<%= form_for @chat_room do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
  </div>

  <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/show.html.erb
<div class="room-header">
  <h1><%= link_to "<span class='glyphicon glyphicon-chevron-left' aria-hidden='true'></span>".html_safe, chat_rooms_path %> <%= @chat_room.title %></h1>
</div>

<div id="messages" data-chat-room-id="<%= @chat_room.id %>">
  <%= render @chat_room.messages %>
  <%#= render :partial => 'chat_rooms/message', locals: {messages: @chat_room.messages} %>
</div>

<%= form_for @message, url: '#' do |f| %>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
    <small class="text-muted">From 2 to 1000 characters</small>
  </div>

  <%= f.submit "Post", class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/home/index.html.erb
<div>
  Hello <%= current_user.name %>!
  <br />
  <%= link_to t('.sign_out', default: 'Sign out'), destroy_user_session_path, method: :delete %>
</div>
<div>
  <%= link_to "View chatrooms", chat_rooms_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat App</title>
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@chatapp" />
    <meta name="twitter:creator" content="@brynmrk" />
    <meta name="twitter:image" content="https://pbs.twimg.com/profile_images/795233551373451264/5Dk2WreB.jpg" />
    <meta name="twitter:image:width" content="375">
    <meta name="twitter:image:height" content="375">
    <meta property="og:url" content="https://chat-app-rails5.herokuapp.com//" />
    <meta property="og:title" content="Chat App" />
    <meta property="og:description" content="Realtime chat app. Chat with your friends!" />
    <meta property="og:image" content="http://i.imgur.com/aLxzmUm.png" />
    <meta name="google-site-verification" content="yFtnYbX35FaGqsvCc-Q6KQeZ62EQ_xidLBhxK_qLZaY" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container-fluid">
      <div class="main-content-wrapper col-xs-12">
        <div class="alert-messages col-xs-12">
          <%= render partial: 'shared/alert_messages' %>
        </div>
        <div class="main-content col-xs-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat App</title>
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@chatapp" />
    <meta name="twitter:creator" content="@brynmrk" />
    <meta name="twitter:image" content="https://pbs.twimg.com/profile_images/795233551373451264/5Dk2WreB.jpg" />
    <meta name="twitter:image:width" content="375">
    <meta name="twitter:image:height" content="375">
    <meta property="og:url" content="https://chat-app-rails5.herokuapp.com//" />
    <meta property="og:title" content="Chat App" />
    <meta property="og:description" content="Realtime chat app. Chat with your friends!" />
    <meta property="og:image" content="http://i.imgur.com/aLxzmUm.png" />
    <meta name="google-site-verification" content="yFtnYbX35FaGqsvCc-Q6KQeZ62EQ_xidLBhxK_qLZaY" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container-fluid">
      <div class="content-wrapper col-xs-12">
        <div class="alert-messages col-xs-12">
          <%= render partial: 'shared/alert_messages' %>
        </div>
        <div class="content col-xs-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/minimal.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat App</title>
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@chatapp" />
    <meta name="twitter:creator" content="@brynmrk" />
    <meta name="twitter:image" content="https://pbs.twimg.com/profile_images/795233551373451264/5Dk2WreB.jpg" />
    <meta name="twitter:image:width" content="375">
    <meta name="twitter:image:height" content="375">
    <meta property="og:url" content="https://chat-app-rails5.herokuapp.com//" />
    <meta property="og:title" content="Chat App" />
    <meta property="og:description" content="Realtime chat app. Chat with your friends!" />
    <meta property="og:image" content="http://i.imgur.com/aLxzmUm.png" />
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-1">
        <%= gravatar_for message.user %>
      </div>
      <div class="col-md-11">
        <p class="card-text">
          <span class="text-muted"><%= message.user.name %> at <%= message.timestamp %> says</span><br>
          <%= message.body %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_alert_messages.html.erb
<% if alert %>
  <p class="alert alert-warning alert-dismissable col-xs-5">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </p>
<% end %>
<% if notice %>
  <p class="alert alert-info alert-dismissable col-xs-5">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </p>
<% end %>